version: "3"
services:
  delegate-app:
    container_name: delegatedapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      NODE_ENV: production
